name: Node.js CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Specify your Node.js version here

    - name: Install dependencies
      run: npm install

    - name: Clean up
      run: npm run clean

    - name: Run Mocha tests
      run: npm test
